# Generated by Django 5.0.1 on 2024-03-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_basic',
            name='payment_status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
