# Generated by Django 5.0.1 on 2024-03-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0003_student_basic_collage_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_basic',
            old_name='collage_status',
            new_name='login_status',
        ),
    ]
