# Generated by Django 5.0.1 on 2024-03-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0004_rename_collage_status_student_basic_login_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_detalis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll', models.IntegerField()),
                ('collage_status', models.IntegerField()),
                ('college_name', models.CharField(max_length=300)),
                ('payment_status', models.IntegerField()),
            ],
            options={
                'db_table': 'student_detalis',
            },
        ),
        migrations.DeleteModel(
            name='student_basic',
        ),
    ]
