# Generated by Django 5.0.1 on 2024-03-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0005_student_detalis_delete_student_basic'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('pwd', models.IntegerField()),
            ],
            options={
                'db_table': 'admin',
            },
        ),
    ]
