# Generated by Django 5.0.1 on 2024-03-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0007_alter_student_detalis_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student_detalis',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='student_detalis',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='student_detalis',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student_detalis',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student_detalis',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='student_detalis',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='student_detalis',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='student_detalis',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='student_detalis',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='student_detalis',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student_detalis',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student_detalis',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='student_detalis',
            name='username',
        ),
    ]
