# Generated by Django 5.0.1 on 2024-03-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0007_event_event_det'),
    ]

    operations = [
        migrations.CreateModel(
            name='events_detalis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('event_name', models.CharField(max_length=100)),
                ('part_no', models.IntegerField()),
            ],
            options={
                'db_table': 'event_detalis',
            },
        ),
        migrations.DeleteModel(
            name='event_det',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='no_of_par',
            new_name='roll',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_name',
        ),
    ]
