# Generated by Django 5.0.1 on 2024-03-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0008_alter_student_detalis_managers_and_more'),
        ('fest_app', '0008_events_detalis_delete_event_det_and_more'),
    ]

    operations = [
    ]
