# Generated by Django 5.0.1 on 2024-03-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0009_merge_20240313_1229'),
        ('fest_app', '0009_student_detalis_id_card_student_detalis_payment_ss'),
    ]

    operations = [
    ]
