# Generated by Django 5.0.1 on 2024-03-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0010_merge_20240329_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('CatWalk', models.IntegerField(default=0)),
                ('DuoDance', models.IntegerField(default=0)),
                ('mintoframe', models.IntegerField(default=0)),
                ('Facepaint', models.IntegerField(default=0)),
                ('rell', models.IntegerField(default=0)),
                ('selfie', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'abc',
            },
        ),
    ]
