# Generated by Django 5.0.1 on 2024-04-13 07:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0011_abc'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detalis',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
