# Generated by Django 4.2.11 on 2024-04-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0015_alter_customuser_options_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_card_image',
            field=models.ImageField(blank=True, upload_to='id_cards/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
