# Generated by Django 4.2.11 on 2024-05-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0019_signuprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
