# Generated by Django 4.2.11 on 2024-05-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0020_customuser_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abc',
        ),
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.DeleteModel(
            name='event',
        ),
        migrations.DeleteModel(
            name='events_detalis',
        ),
        migrations.DeleteModel(
            name='student_detalis',
        ),
    ]
