# Generated by Django 4.2.11 on 2024-05-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0021_delete_abc_delete_admin_delete_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTotals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('catwalk', 'Catwalk'), ('duodance', 'Duo Dance'), ('twomintofame', 'Two Minutes to Fame'), ('facepaint', 'Facepaint'), ('rell', 'Rell'), ('selfie', 'Selfie')], max_length=20, unique=True)),
                ('total_users', models.IntegerField(default=0)),
            ],
        ),
    ]
