# Generated by Django 4.2.11 on 2024-05-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0024_remove_catwalkteam_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catwalkteam',
            name='team_members',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
