# Generated by Django 4.2.11 on 2024-05-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0025_catwalkteam_team_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatwalkTeamMember',
        ),
    ]
