# Generated by Django 4.2.11 on 2024-05-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0026_delete_catwalkteammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuoDanceTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('leader_roll_number', models.CharField(max_length=100)),
                ('team_members', models.CharField(max_length=255)),
            ],
        ),
    ]
