# Generated by Django 4.2.11 on 2024-09-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0027_duodanceteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CatwalkTeam',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='DuoDanceTeam',
        ),
        migrations.DeleteModel(
            name='SignupRequest',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
